#!/usr/bin/env nextflow
nextflow.enable.dsl=2

// Parameters
params.datafiles = "$HOME/data/*"

//Pre-processing
process a {
    // env (if needed
    
    input:
    path process_path

    // output?

    script:
    """
    echo "Processing file: $x"
    // commmand
    """
}

// Process X

// Workflow

workflow {
    // Create channel for data files
    datafiles_ch = Channel.fromPath(param.datafiles)

    //Pass channel through processes
}

// Outputs (if not already generated by processes?)